### ISSUE TITLE
Komentář

### ISSUE THREAD

**Issue by Amatthe** [LucieMusilova/PROJEKT-Grid-blog#1]
Ahoj,

líbí se mi, jaks to vyřešila, včetně responzivní verze. Na hodně velký obrazovce jsou ty obrázky už docela pixelovatý, takže bych navrhnul nastavení maximální šířky, a možná zarovnání textu elementu blockquote na střed, aby to vypadalo hezky, i když se zalomí.

**Comment by LucieMusilova** [comment]
@Amatthe 

Ahoj Matěji, 

vše jsem upravila a vypadá to mnohem líp.:) Děkuji za tipy! :)

L.
